package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="warehouse"
)
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private String adr1;
     private String adr2;
     private String city;
     private String contact;
     private String firstName;
     private Set<JobCard> jobCards = new HashSet<JobCard>(0);
     private String lastName;
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);
     private UserType userType;
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public Customer() {
    }

	
    public Customer(UserType userType) {
        this.userType = userType;
    }
    public Customer(String adr1, String adr2, String city, String contact, String firstName, Set<JobCard> jobCards, String lastName, Set<UserLogin> userLogins, UserType userType, Set<Vehicle> vehicles) {
       this.adr1 = adr1;
       this.adr2 = adr2;
       this.city = city;
       this.contact = contact;
       this.firstName = firstName;
       this.jobCards = jobCards;
       this.lastName = lastName;
       this.userLogins = userLogins;
       this.userType = userType;
       this.vehicles = vehicles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CUSTOMER_ID", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="ADR1", length=45)
    public String getAdr1() {
        return this.adr1;
    }
    
    public void setAdr1(String adr1) {
        this.adr1 = adr1;
    }

    
    @Column(name="ADR2", length=45)
    public String getAdr2() {
        return this.adr2;
    }
    
    public void setAdr2(String adr2) {
        this.adr2 = adr2;
    }

    
    @Column(name="CITY", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="CONTACT", length=45)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    
    @Column(name="FIRST_NAME", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<JobCard> getJobCards() {
        return this.jobCards;
    }
    
    public void setJobCards(Set<JobCard> jobCards) {
        this.jobCards = jobCards;
    }

    
    @Column(name="LAST_NAME", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_TYPE_ID", nullable=false)
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }




}


