package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name="history"
    ,catalog="warehouse"
)
public class History  implements java.io.Serializable {


     private Integer idhistory;
     private Module module;
     private Task task;
     private UserLogin userLogin;
     private String remark;
     private Date date;

    public History() {
    }

    public History(Module module, Task task, UserLogin userLogin, String remark, Date date) {
       this.module = module;
       this.task = task;
       this.userLogin = userLogin;
       this.remark = remark;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idhistory", unique=true, nullable=false)
    public Integer getIdhistory() {
        return this.idhistory;
    }
    
    public void setIdhistory(Integer idhistory) {
        this.idhistory = idhistory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODULE")
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OPERATION")
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USR_ID")
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

    
    @Column(name="REMARK", length=45)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


