package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobCardServices generated by hbm2java
 */
@Entity
@Table(name="job_card_services"
    ,catalog="warehouse"
)
public class JobCardServices  implements java.io.Serializable {


     private Integer id;
     private JobCard jobCard;
     private Services services;
     private Status status;
     private UserLogin userLogin;

    public JobCardServices() {
    }

    public JobCardServices(JobCard jobCard, Services services, Status status, UserLogin userLogin) {
       this.jobCard = jobCard;
       this.services = services;
       this.status = status;
       this.userLogin = userLogin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOB_CARD_ID", nullable=false)
    public JobCard getJobCard() {
        return this.jobCard;
    }
    
    public void setJobCard(JobCard jobCard) {
        this.jobCard = jobCard;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SERVICES_ID", nullable=false)
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ID", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_LOGIN_ID", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }




}


