package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="module"
    ,catalog="warehouse"
)
public class Module  implements java.io.Serializable {


     private int moduleCode;
     private String description;
     private Set<Section> sections = new HashSet<Section>(0);
     private Set<History> histories = new HashSet<History>(0);
     private Set<UserPrivilage> userPrivilages = new HashSet<UserPrivilage>(0);

    public Module() {
    }

	
    public Module(int moduleCode) {
        this.moduleCode = moduleCode;
    }
    public Module(int moduleCode, String description, Set<Section> sections, Set<History> histories, Set<UserPrivilage> userPrivilages) {
       this.moduleCode = moduleCode;
       this.description = description;
       this.sections = sections;
       this.histories = histories;
       this.userPrivilages = userPrivilages;
    }
   
     @Id 

    
    @Column(name="MODULE_CODE", unique=true, nullable=false)
    public int getModuleCode() {
        return this.moduleCode;
    }
    
    public void setModuleCode(int moduleCode) {
        this.moduleCode = moduleCode;
    }

    
    @Column(name="DESCRIPTION", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<Section> getSections() {
        return this.sections;
    }
    
    public void setSections(Set<Section> sections) {
        this.sections = sections;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<History> getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<UserPrivilage> getUserPrivilages() {
        return this.userPrivilages;
    }
    
    public void setUserPrivilages(Set<UserPrivilage> userPrivilages) {
        this.userPrivilages = userPrivilages;
    }




}


