package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDealer generated by hbm2java
 */
@Entity
@Table(name="order_dealer"
    ,catalog="warehouse"
)
public class OrderDealer  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private Dealer dealer;
     private PurchasingOrder purchasingOrder;

    public OrderDealer() {
    }

	
    public OrderDealer(Dealer dealer, PurchasingOrder purchasingOrder) {
        this.dealer = dealer;
        this.purchasingOrder = purchasingOrder;
    }
    public OrderDealer(Date date, Dealer dealer, PurchasingOrder purchasingOrder) {
       this.date = date;
       this.dealer = dealer;
       this.purchasingOrder = purchasingOrder;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEALER_DEALER", nullable=false)
    public Dealer getDealer() {
        return this.dealer;
    }
    
    public void setDealer(Dealer dealer) {
        this.dealer = dealer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORDER_ORDER", nullable=false)
    public PurchasingOrder getPurchasingOrder() {
        return this.purchasingOrder;
    }
    
    public void setPurchasingOrder(PurchasingOrder purchasingOrder) {
        this.purchasingOrder = purchasingOrder;
    }




}


