package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SectionTaskId generated by hbm2java
 */
@Embeddable
public class SectionTaskId  implements java.io.Serializable {


     private int sectionSectionCode;
     private int taskTaskId;

    public SectionTaskId() {
    }

    public SectionTaskId(int sectionSectionCode, int taskTaskId) {
       this.sectionSectionCode = sectionSectionCode;
       this.taskTaskId = taskTaskId;
    }
   


    @Column(name="SECTION_SECTION_CODE", nullable=false)
    public int getSectionSectionCode() {
        return this.sectionSectionCode;
    }
    
    public void setSectionSectionCode(int sectionSectionCode) {
        this.sectionSectionCode = sectionSectionCode;
    }


    @Column(name="TASK_TASK_ID", nullable=false)
    public int getTaskTaskId() {
        return this.taskTaskId;
    }
    
    public void setTaskTaskId(int taskTaskId) {
        this.taskTaskId = taskTaskId;
    }




}


