package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status"
    ,catalog="warehouse"
)
public class Status  implements java.io.Serializable {


     private int statusId;
     private Set<JobCard> jobCards = new HashSet<JobCard>(0);
     private Set<PurchasingOrder> purchasingOrders = new HashSet<PurchasingOrder>(0);
     private String status;
     private String type;
     private Set<WarehouseItem> warehouseItems = new HashSet<WarehouseItem>(0);

    public Status() {
    }

	
    public Status(int statusId) {
        this.statusId = statusId;
    }
    public Status(int statusId, Set<JobCard> jobCards, Set<PurchasingOrder> purchasingOrders, String status, String type, Set<WarehouseItem> warehouseItems) {
       this.statusId = statusId;
       this.jobCards = jobCards;
       this.purchasingOrders = purchasingOrders;
       this.status = status;
       this.type = type;
       this.warehouseItems = warehouseItems;
    }
   
     @Id 

    
    @Column(name="STATUS_ID", unique=true, nullable=false)
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<JobCard> getJobCards() {
        return this.jobCards;
    }
    
    public void setJobCards(Set<JobCard> jobCards) {
        this.jobCards = jobCards;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<PurchasingOrder> getPurchasingOrders() {
        return this.purchasingOrders;
    }
    
    public void setPurchasingOrders(Set<PurchasingOrder> purchasingOrders) {
        this.purchasingOrders = purchasingOrders;
    }

    
    @Column(name="STATUS", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="TYPE", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<WarehouseItem> getWarehouseItems() {
        return this.warehouseItems;
    }
    
    public void setWarehouseItems(Set<WarehouseItem> warehouseItems) {
        this.warehouseItems = warehouseItems;
    }




}


