package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StockItem generated by hbm2java
 */
@Entity
@Table(name="stock_item"
    ,catalog="warehouse"
)
public class StockItem  implements java.io.Serializable {


     private Integer stockItemId;
     private Date buyDate;
     private PurchasingOrder purchasingOrder;
     private Double qnty;
     private Double saleCost;
     private Double unitCost;
     private WarehouseItem warehouseItem;

    public StockItem() {
    }

	
    public StockItem(PurchasingOrder purchasingOrder, WarehouseItem warehouseItem) {
        this.purchasingOrder = purchasingOrder;
        this.warehouseItem = warehouseItem;
    }
    public StockItem(Date buyDate, PurchasingOrder purchasingOrder, Double qnty, Double saleCost, Double unitCost, WarehouseItem warehouseItem) {
       this.buyDate = buyDate;
       this.purchasingOrder = purchasingOrder;
       this.qnty = qnty;
       this.saleCost = saleCost;
       this.unitCost = unitCost;
       this.warehouseItem = warehouseItem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STOCK_ITEM_ID", unique=true, nullable=false)
    public Integer getStockItemId() {
        return this.stockItemId;
    }
    
    public void setStockItemId(Integer stockItemId) {
        this.stockItemId = stockItemId;
    }

    
    @Column(name="buyDate", length=26)
    public Date getBuyDate() {
        return this.buyDate;
    }
    
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PURCHASING_ORDER", nullable=false)
    public PurchasingOrder getPurchasingOrder() {
        return this.purchasingOrder;
    }
    
    public void setPurchasingOrder(PurchasingOrder purchasingOrder) {
        this.purchasingOrder = purchasingOrder;
    }

    
    @Column(name="QNTY", precision=22, scale=0)
    public Double getQnty() {
        return this.qnty;
    }
    
    public void setQnty(Double qnty) {
        this.qnty = qnty;
    }

    
    @Column(name="saleCost", precision=22, scale=0)
    public Double getSaleCost() {
        return this.saleCost;
    }
    
    public void setSaleCost(Double saleCost) {
        this.saleCost = saleCost;
    }

    
    @Column(name="perUnitCost", precision=22, scale=0)
    public Double getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(Double unitCost) {
        this.unitCost = unitCost;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WAREHOUSE_ITEM_ID", nullable=false)
    public WarehouseItem getWarehouseItem() {
        return this.warehouseItem;
    }
    
    public void setWarehouseItem(WarehouseItem warehouseItem) {
        this.warehouseItem = warehouseItem;
    }




}


