package com.myapp.mapping;
// Generated Oct 27, 2018 9:02:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name="user_login"
    ,catalog="warehouse"
)
public class UserLogin  implements java.io.Serializable {


     private Integer userLoginId;
     private Customer customer;
     private String userName;
     private String password;
     private Integer status;
     private Set<History> histories = new HashSet<History>(0);
     private Set<JobCard> jobCards = new HashSet<JobCard>(0);
     private Set<JobCardItem> jobCardItems = new HashSet<JobCardItem>(0);
     private Set<JobCardServices> jobCardServiceses = new HashSet<JobCardServices>(0);

    public UserLogin() {
    }

	
    public UserLogin(Customer customer) {
        this.customer = customer;
    }
    public UserLogin(Customer customer, String userName, String password, Integer status, Set<History> histories, Set<JobCard> jobCards, Set<JobCardItem> jobCardItems, Set<JobCardServices> jobCardServiceses) {
       this.customer = customer;
       this.userName = userName;
       this.password = password;
       this.status = status;
       this.histories = histories;
       this.jobCards = jobCards;
       this.jobCardItems = jobCardItems;
       this.jobCardServiceses = jobCardServiceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USER_LOGIN_ID", unique=true, nullable=false)
    public Integer getUserLoginId() {
        return this.userLoginId;
    }
    
    public void setUserLoginId(Integer userLoginId) {
        this.userLoginId = userLoginId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="USER_NAME", length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="PASSWORD", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<History> getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<JobCard> getJobCards() {
        return this.jobCards;
    }
    
    public void setJobCards(Set<JobCard> jobCards) {
        this.jobCards = jobCards;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<JobCardItem> getJobCardItems() {
        return this.jobCardItems;
    }
    
    public void setJobCardItems(Set<JobCardItem> jobCardItems) {
        this.jobCardItems = jobCardItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<JobCardServices> getJobCardServiceses() {
        return this.jobCardServiceses;
    }
    
    public void setJobCardServiceses(Set<JobCardServices> jobCardServiceses) {
        this.jobCardServiceses = jobCardServiceses;
    }




}


