package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WarehouseItem generated by hbm2java
 */
@Entity
@Table(name="warehouse_item"
    ,catalog="warehouse"
)
public class WarehouseItem  implements java.io.Serializable {


     private Integer itemId;
     private Brand brand;
     private Category category;
     private String itemName;
     private Status status;
     private Set<StockItem> stockItems = new HashSet<StockItem>(0);

    public WarehouseItem() {
    }

	
    public WarehouseItem(Brand brand, Category category, Status status) {
        this.brand = brand;
        this.category = category;
        this.status = status;
    }
    public WarehouseItem(Brand brand, Category category, String itemName, Status status, Set<StockItem> stockItems) {
       this.brand = brand;
       this.category = category;
       this.itemName = itemName;
       this.status = status;
       this.stockItems = stockItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ITEM_ID", unique=true, nullable=false)
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BRAND_ID", nullable=false)
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORY_ID", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="ITEM_NAME", length=45)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ID", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="warehouseItem")
    public Set<StockItem> getStockItems() {
        return this.stockItems;
    }
    
    public void setStockItems(Set<StockItem> stockItems) {
        this.stockItems = stockItems;
    }




}


