package com.myapp.mapping;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name="warehouse"
    ,catalog="warehouse"
)
public class Warehouse  implements java.io.Serializable {


     private Integer warehouseId;
     private String location;
     private Set<Racks> rackses = new HashSet<Racks>(0);

    public Warehouse() {
    }

    public Warehouse(String location, Set<Racks> rackses) {
       this.location = location;
       this.rackses = rackses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="WAREHOUSE_ID", unique=true, nullable=false)
    public Integer getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    
    @Column(name="LOCATION", length=45)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="warehouse")
    public Set<Racks> getRackses() {
        return this.rackses;
    }
    
    public void setRackses(Set<Racks> rackses) {
        this.rackses = rackses;
    }




}


