package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="warehouse"
)
public class Category  implements java.io.Serializable {


     private Integer categoryId;
     private String category;
     private Set<WarehouseItem> warehouseItems = new HashSet<WarehouseItem>(0);

    public Category() {
    }

    public Category(String category, Set<WarehouseItem> warehouseItems) {
       this.category = category;
       this.warehouseItems = warehouseItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CATEGORY_ID", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="CATEGORY", length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<WarehouseItem> getWarehouseItems() {
        return this.warehouseItems;
    }
    
    public void setWarehouseItems(Set<WarehouseItem> warehouseItems) {
        this.warehouseItems = warehouseItems;
    }




}


