package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CellItem generated by hbm2java
 */
@Entity
@Table(name="cell_item"
    ,catalog="warehouse"
)
public class CellItem  implements java.io.Serializable {


     private Integer id;
     private Cell cell;
     private StockItem stockItem;
     private Double qnty;

    public CellItem() {
    }

	
    public CellItem(Cell cell, StockItem stockItem) {
        this.cell = cell;
        this.stockItem = stockItem;
    }
    public CellItem(Cell cell, StockItem stockItem, Double qnty) {
       this.cell = cell;
       this.stockItem = stockItem;
       this.qnty = qnty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CELL_CELL", nullable=false)
    public Cell getCell() {
        return this.cell;
    }
    
    public void setCell(Cell cell) {
        this.cell = cell;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STOCK_ITEM_ID", nullable=false)
    public StockItem getStockItem() {
        return this.stockItem;
    }
    
    public void setStockItem(StockItem stockItem) {
        this.stockItem = stockItem;
    }

    
    @Column(name="QNTY", precision=22, scale=0)
    public Double getQnty() {
        return this.qnty;
    }
    
    public void setQnty(Double qnty) {
        this.qnty = qnty;
    }




}


