package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cell generated by hbm2java
 */
@Entity
@Table(name="cell"
    ,catalog="warehouse"
)
public class Cell  implements java.io.Serializable {


     private Integer cell;
     private Racks racks;
     private String XCode;
     private String YCode;
     private Double maxStorage;
     private Set<CellItem> cellItems = new HashSet<CellItem>(0);

    public Cell() {
    }

	
    public Cell(Racks racks) {
        this.racks = racks;
    }
    public Cell(Racks racks, String XCode, String YCode, Double maxStorage, Set<CellItem> cellItems) {
       this.racks = racks;
       this.XCode = XCode;
       this.YCode = YCode;
       this.maxStorage = maxStorage;
       this.cellItems = cellItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CELL", unique=true, nullable=false)
    public Integer getCell() {
        return this.cell;
    }
    
    public void setCell(Integer cell) {
        this.cell = cell;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RACKS_ID", nullable=false)
    public Racks getRacks() {
        return this.racks;
    }
    
    public void setRacks(Racks racks) {
        this.racks = racks;
    }

    
    @Column(name="X_CODE", length=45)
    public String getXCode() {
        return this.XCode;
    }
    
    public void setXCode(String XCode) {
        this.XCode = XCode;
    }

    
    @Column(name="Y_CODE", length=45)
    public String getYCode() {
        return this.YCode;
    }
    
    public void setYCode(String YCode) {
        this.YCode = YCode;
    }

    
    @Column(name="MAX_STORAGE", precision=22, scale=0)
    public Double getMaxStorage() {
        return this.maxStorage;
    }
    
    public void setMaxStorage(Double maxStorage) {
        this.maxStorage = maxStorage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cell")
    public Set<CellItem> getCellItems() {
        return this.cellItems;
    }
    
    public void setCellItems(Set<CellItem> cellItems) {
        this.cellItems = cellItems;
    }




}


