package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemOrder generated by hbm2java
 */
@Entity
@Table(name="item_order"
    ,catalog="warehouse"
)
public class ItemOrder  implements java.io.Serializable {


     private Integer id;
     private PurchasingOrder purchasingOrder;
     private WarehouseItem warehouseItem;
     private Double qnty;

    public ItemOrder() {
    }

	
    public ItemOrder(PurchasingOrder purchasingOrder, WarehouseItem warehouseItem) {
        this.purchasingOrder = purchasingOrder;
        this.warehouseItem = warehouseItem;
    }
    public ItemOrder(PurchasingOrder purchasingOrder, WarehouseItem warehouseItem, Double qnty) {
       this.purchasingOrder = purchasingOrder;
       this.warehouseItem = warehouseItem;
       this.qnty = qnty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORDER_ORDER", nullable=false)
    public PurchasingOrder getPurchasingOrder() {
        return this.purchasingOrder;
    }
    
    public void setPurchasingOrder(PurchasingOrder purchasingOrder) {
        this.purchasingOrder = purchasingOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WAREHOUSE_ITEM_ITEM_ID", nullable=false)
    public WarehouseItem getWarehouseItem() {
        return this.warehouseItem;
    }
    
    public void setWarehouseItem(WarehouseItem warehouseItem) {
        this.warehouseItem = warehouseItem;
    }

    
    @Column(name="QNTY", precision=22, scale=0)
    public Double getQnty() {
        return this.qnty;
    }
    
    public void setQnty(Double qnty) {
        this.qnty = qnty;
    }




}


