package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobCardItem generated by hbm2java
 */
@Entity
@Table(name="job_card_item"
    ,catalog="warehouse"
)
public class JobCardItem  implements java.io.Serializable {


     private Integer id;
     private JobCard jobCard;
     private Status status;
     private StockItem stockItem;
     private UserLogin userLogin;

    public JobCardItem() {
    }

    public JobCardItem(JobCard jobCard, Status status, StockItem stockItem, UserLogin userLogin) {
       this.jobCard = jobCard;
       this.status = status;
       this.stockItem = stockItem;
       this.userLogin = userLogin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOB_CARD_ID", nullable=false)
    public JobCard getJobCard() {
        return this.jobCard;
    }
    
    public void setJobCard(JobCard jobCard) {
        this.jobCard = jobCard;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ID", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STOCK_ITEM_ID", nullable=false)
    public StockItem getStockItem() {
        return this.stockItem;
    }
    
    public void setStockItem(StockItem stockItem) {
        this.stockItem = stockItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_LOGIN_ID", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }




}


