package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobCard generated by hbm2java
 */
@Entity
@Table(name="job_card"
    ,catalog="warehouse"
)
public class JobCard  implements java.io.Serializable {


     private Integer jobCardId;
     private Customer customer;
     private Status status;
     private UserLogin userLogin;
     private Date jobDate;
     private Set<JobCardItem> jobCardItems = new HashSet<JobCardItem>(0);
     private Set<JobCardServices> jobCardServiceses = new HashSet<JobCardServices>(0);

    public JobCard() {
    }

	
    public JobCard(Customer customer, Status status, UserLogin userLogin) {
        this.customer = customer;
        this.status = status;
        this.userLogin = userLogin;
    }
    public JobCard(Customer customer, Status status, UserLogin userLogin, Date jobDate, Set<JobCardItem> jobCardItems, Set<JobCardServices> jobCardServiceses) {
       this.customer = customer;
       this.status = status;
       this.userLogin = userLogin;
       this.jobDate = jobDate;
       this.jobCardItems = jobCardItems;
       this.jobCardServiceses = jobCardServiceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="JOB_CARD_ID", unique=true, nullable=false)
    public Integer getJobCardId() {
        return this.jobCardId;
    }
    
    public void setJobCardId(Integer jobCardId) {
        this.jobCardId = jobCardId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ID", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_LOGIN_ID", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="JOB_DATE", length=19)
    public Date getJobDate() {
        return this.jobDate;
    }
    
    public void setJobDate(Date jobDate) {
        this.jobDate = jobDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobCard")
    public Set<JobCardItem> getJobCardItems() {
        return this.jobCardItems;
    }
    
    public void setJobCardItems(Set<JobCardItem> jobCardItems) {
        this.jobCardItems = jobCardItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobCard")
    public Set<JobCardServices> getJobCardServiceses() {
        return this.jobCardServiceses;
    }
    
    public void setJobCardServiceses(Set<JobCardServices> jobCardServiceses) {
        this.jobCardServiceses = jobCardServiceses;
    }




}


