package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Racks generated by hbm2java
 */
@Entity
@Table(name="racks"
    ,catalog="warehouse"
)
public class Racks  implements java.io.Serializable {


     private Integer racksId;
     private Warehouse warehouse;
     private String rack;
     private Set<Cell> cells = new HashSet<Cell>(0);

    public Racks() {
    }

	
    public Racks(Warehouse warehouse) {
        this.warehouse = warehouse;
    }
    public Racks(Warehouse warehouse, String rack, Set<Cell> cells) {
       this.warehouse = warehouse;
       this.rack = rack;
       this.cells = cells;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RACKS_ID", unique=true, nullable=false)
    public Integer getRacksId() {
        return this.racksId;
    }
    
    public void setRacksId(Integer racksId) {
        this.racksId = racksId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WAREHOUSE_ID", nullable=false)
    public Warehouse getWarehouse() {
        return this.warehouse;
    }
    
    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    
    @Column(name="RACK", length=45)
    public String getRack() {
        return this.rack;
    }
    
    public void setRack(String rack) {
        this.rack = rack;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="racks")
    public Set<Cell> getCells() {
        return this.cells;
    }
    
    public void setCells(Set<Cell> cells) {
        this.cells = cells;
    }




}


