package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SectionTaskId generated by hbm2java
 */
@Embeddable
public class SectionTaskId  implements java.io.Serializable {


     private int sectionSectionCode;
     private int taskTaskId;

    public SectionTaskId() {
    }

    public SectionTaskId(int sectionSectionCode, int taskTaskId) {
       this.sectionSectionCode = sectionSectionCode;
       this.taskTaskId = taskTaskId;
    }
   


    @Column(name="SECTION_SECTION_CODE", nullable=false)
    public int getSectionSectionCode() {
        return this.sectionSectionCode;
    }
    
    public void setSectionSectionCode(int sectionSectionCode) {
        this.sectionSectionCode = sectionSectionCode;
    }


    @Column(name="TASK_TASK_ID", nullable=false)
    public int getTaskTaskId() {
        return this.taskTaskId;
    }
    
    public void setTaskTaskId(int taskTaskId) {
        this.taskTaskId = taskTaskId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SectionTaskId) ) return false;
		 SectionTaskId castOther = ( SectionTaskId ) other; 
         
		 return (this.getSectionSectionCode()==castOther.getSectionSectionCode())
 && (this.getTaskTaskId()==castOther.getTaskTaskId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSectionSectionCode();
         result = 37 * result + this.getTaskTaskId();
         return result;
   }   


}


