package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name="services"
    ,catalog="warehouse"
)
public class Services  implements java.io.Serializable {


     private Integer serviceId;
     private String services;
     private Set<JobCardServices> jobCardServiceses = new HashSet<JobCardServices>(0);

    public Services() {
    }

    public Services(String services, Set<JobCardServices> jobCardServiceses) {
       this.services = services;
       this.jobCardServiceses = jobCardServiceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SERVICE_ID", unique=true, nullable=false)
    public Integer getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    
    @Column(name="SERVICES", length=45)
    public String getServices() {
        return this.services;
    }
    
    public void setServices(String services) {
        this.services = services;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<JobCardServices> getJobCardServiceses() {
        return this.jobCardServiceses;
    }
    
    public void setJobCardServiceses(Set<JobCardServices> jobCardServiceses) {
        this.jobCardServiceses = jobCardServiceses;
    }




}


