package mapping.copy;
// Generated Nov 10, 2018 4:53:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockItem generated by hbm2java
 */
@Entity
@Table(name="stock_item"
    ,catalog="warehouse"
)
public class StockItem  implements java.io.Serializable {


     private Integer stockItemId;
     private PurchasingOrder purchasingOrder;
     private WarehouseItem warehouseItem;
     private Double qnty;
     private Double perUnitCost;
     private Double saleCost;
     private Date buyDate;
     private Set<CellItem> cellItems = new HashSet<CellItem>(0);
     private Set<JobCardItem> jobCardItems = new HashSet<JobCardItem>(0);

    public StockItem() {
    }

	
    public StockItem(PurchasingOrder purchasingOrder, WarehouseItem warehouseItem) {
        this.purchasingOrder = purchasingOrder;
        this.warehouseItem = warehouseItem;
    }
    public StockItem(PurchasingOrder purchasingOrder, WarehouseItem warehouseItem, Double qnty, Double perUnitCost, Double saleCost, Date buyDate, Set<CellItem> cellItems, Set<JobCardItem> jobCardItems) {
       this.purchasingOrder = purchasingOrder;
       this.warehouseItem = warehouseItem;
       this.qnty = qnty;
       this.perUnitCost = perUnitCost;
       this.saleCost = saleCost;
       this.buyDate = buyDate;
       this.cellItems = cellItems;
       this.jobCardItems = jobCardItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STOCK_ITEM_ID", unique=true, nullable=false)
    public Integer getStockItemId() {
        return this.stockItemId;
    }
    
    public void setStockItemId(Integer stockItemId) {
        this.stockItemId = stockItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PURCHASING_ORDER", nullable=false)
    public PurchasingOrder getPurchasingOrder() {
        return this.purchasingOrder;
    }
    
    public void setPurchasingOrder(PurchasingOrder purchasingOrder) {
        this.purchasingOrder = purchasingOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WAREHOUSE_ITEM_ID", nullable=false)
    public WarehouseItem getWarehouseItem() {
        return this.warehouseItem;
    }
    
    public void setWarehouseItem(WarehouseItem warehouseItem) {
        this.warehouseItem = warehouseItem;
    }

    
    @Column(name="QNTY", precision=22, scale=0)
    public Double getQnty() {
        return this.qnty;
    }
    
    public void setQnty(Double qnty) {
        this.qnty = qnty;
    }

    
    @Column(name="perUnitCost", precision=22, scale=0)
    public Double getPerUnitCost() {
        return this.perUnitCost;
    }
    
    public void setPerUnitCost(Double perUnitCost) {
        this.perUnitCost = perUnitCost;
    }

    
    @Column(name="saleCost", precision=22, scale=0)
    public Double getSaleCost() {
        return this.saleCost;
    }
    
    public void setSaleCost(Double saleCost) {
        this.saleCost = saleCost;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="buyDate", length=10)
    public Date getBuyDate() {
        return this.buyDate;
    }
    
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stockItem")
    public Set<CellItem> getCellItems() {
        return this.cellItems;
    }
    
    public void setCellItems(Set<CellItem> cellItems) {
        this.cellItems = cellItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stockItem")
    public Set<JobCardItem> getJobCardItems() {
        return this.jobCardItems;
    }
    
    public void setJobCardItems(Set<JobCardItem> jobCardItems) {
        this.jobCardItems = jobCardItems;
    }




}


